# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from godaddy_python_sdk.pydantic.error_field import ErrorField

class ActionReason(BaseModel):
    # Short identifier, suitable for indicating the reason for the current status and how to handle within client code
    code: str = Field(alias='code')

    # List of the specific fields, and the errors found with their contents
    fields: typing.Optional[typing.List[ErrorField]] = Field(None, alias='fields')

    # Human-readable, English description of the code
    message: typing.Optional[str] = Field(None, alias='message')
    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
