# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ConsentRedemption(BaseModel):
    # Timestamp indicating when the end-user consented to these legal agreements
    agreed_at: str = Field(alias='agreedAt')

    # Originating client IP address of the end-user's computer when they consented to these legal agreements
    agreed_by: str = Field(alias='agreedBy')

    # Currency in which the `price` and `fee` are listed
    currency: str = Field(alias='currency')

    # Fee charged for the domain redemption. Please use GET /v2/customers/{customerId}/domains/{domain} to retrieve the redemption fee and currency for the domain
    fee: int = Field(alias='fee')

    # Price for the domain renewal (if domain renewal required for redemption). Please use GET /v2/customers/{customerId}/domains/{domain} to retrieve the redemption price and currency for the domain
    price: int = Field(alias='price')
    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
