# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class DNSRecordCreateTypeName(BaseModel):
    data: str = Field(alias='data')

    # Service port (SRV only)
    port: typing.Optional[int] = Field(None, alias='port')

    # Record priority (MX and SRV only)
    priority: typing.Optional[int] = Field(None, alias='priority')

    # Service protocol (SRV only)
    protocol: typing.Optional[str] = Field(None, alias='protocol')

    # Service type (SRV only)
    service: typing.Optional[str] = Field(None, alias='service')

    ttl: typing.Optional[int] = Field(None, alias='ttl')

    # Record weight (SRV only)
    weight: typing.Optional[int] = Field(None, alias='weight')
    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
