# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from godaddy_python_sdk.pydantic.contact import Contact

class DomainsContactsBulk(BaseModel):
    # An array of domain names to be validated against. Alternatively, you can specify the extracted tlds. However, full domain names are required if the tld is `uk`
    domains: typing.List[str] = Field(alias='domains')

    contact_admin: typing.Optional[Contact] = Field(None, alias='contactAdmin')

    contact_billing: typing.Optional[Contact] = Field(None, alias='contactBilling')

    contact_presence: typing.Optional[Contact] = Field(None, alias='contactPresence')

    contact_registrant: typing.Optional[Contact] = Field(None, alias='contactRegistrant')

    contact_tech: typing.Optional[Contact] = Field(None, alias='contactTech')

    # Canadian Presence Requirement (CA)
    entity_type: typing.Optional[Literal["ABORIGINAL", "ASSOCIATION", "CITIZEN", "CORPORATION", "EDUCATIONAL", "GOVERNMENT", "HOSPITAL", "INDIAN_BAND", "LEGAL_REPRESENTATIVE", "LIBRARY_ARCHIVE_MUSEUM", "MARK_REGISTERED", "MARK_TRADE", "PARTNERSHIP", "POLITICAL_PARTY", "RESIDENT_PERMANENT", "TRUST", "UNION"]] = Field(None, alias='entityType')
    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
