# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from godaddy_python_sdk.pydantic.consent_v2 import ConsentV2
from godaddy_python_sdk.pydantic.domain_contacts_create_v2 import DomainContactsCreateV2

class DomainPurchaseV2(BaseModel):
    consent: ConsentV2 = Field(alias='consent')

    # For internationalized domain names with non-ascii characters, the domain name is converted to punycode before format and pattern validation rules are checked
    domain: str = Field(alias='domain')

    contacts: typing.Optional[DomainContactsCreateV2] = Field(None, alias='contacts')

    # The domain eligibility data fields as specified by GET /v2/customers/{customerId}/domains/register/schema/{tld}
    metadata: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='metadata')

    name_servers: typing.Optional[typing.List[str]] = Field(None, alias='nameServers')

    period: typing.Optional[int] = Field(None, alias='period')

    privacy: typing.Optional[bool] = Field(None, alias='privacy')

    renew_auto: typing.Optional[bool] = Field(None, alias='renewAuto')
    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
