# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from godaddy_python_sdk.pydantic.consent import Consent
from godaddy_python_sdk.pydantic.contact import Contact

class DomainTransferIn(BaseModel):
    # Authorization code from registrar for transferring a domain
    auth_code: str = Field(alias='authCode')

    consent: Consent = Field(alias='consent')

    contact_admin: typing.Optional[Contact] = Field(None, alias='contactAdmin')

    contact_billing: typing.Optional[Contact] = Field(None, alias='contactBilling')

    contact_registrant: typing.Optional[Contact] = Field(None, alias='contactRegistrant')

    contact_tech: typing.Optional[Contact] = Field(None, alias='contactTech')

    # Can be more than 1 but no more than 10 years total including current registration length
    period: typing.Optional[int] = Field(None, alias='period')

    # Whether or not privacy has been requested
    privacy: typing.Optional[bool] = Field(None, alias='privacy')

    # Whether or not the domain should be configured to automatically renew
    renew_auto: typing.Optional[bool] = Field(None, alias='renewAuto')
    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
