# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ErrorFieldDomainContactsValidate(BaseModel):
    # Short identifier for the error, suitable for indicating the specific error within client code
    code: str = Field(alias='code')

    # An array of domain names the error is for. If tlds are specified in the request, `domains` will contain tlds. For example, if `domains` in request is [\"test1.com\", \"test2.uk\", \"net\"], and the field is invalid for com and net, then one of the `fields` in response will have [\"test1.com\", \"net\"] as `domains`
    domains: typing.List[str] = Field(alias='domains')

    # 1) JSONPath referring to the field within the data containing an error<br/>or<br/>2) JSONPath referring to an object containing an error
    path: str = Field(alias='path')

    # Human-readable, English description of the problem with the contents of the field
    message: typing.Optional[str] = Field(None, alias='message')

    # JSONPath referring to the field on the object referenced by `path` containing an error
    path_related: typing.Optional[str] = Field(None, alias='pathRelated')
    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
