# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class LegalAgreement(BaseModel):
    # Title of the legal agreement
    title: str = Field(alias='title')

    # Unique identifier for the legal agreement
    agreement_key: str = Field(alias='agreementKey')

    # Contents of the legal agreement, suitable for embedding
    content: str = Field(alias='content')

    # URL to a page containing the legal agreement
    url: typing.Optional[str] = Field(None, alias='url')
    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
