# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class RenewalDetails(BaseModel):
    # Currency in which the `price` is listed
    currency: str = Field(alias='currency')

    # Price for the domain renewal excluding taxes or fees
    price: int = Field(alias='price')

    # Whether or not the domain is eligble for renewal based on status
    renewable: typing.Optional[bool] = Field(None, alias='renewable')
    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
