# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import godaddy_python_sdk
from godaddy_python_sdk.model.v1_suggest_alternate_domains200_response import V1SuggestAlternateDomains200Response
from godaddy_python_sdk import configuration


class TestV1SuggestAlternateDomains200Response(unittest.TestCase):
    """V1SuggestAlternateDomains200Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
