# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import godaddy_python_sdk
from godaddy_python_sdk.model.v1_check_domain_availability_post_request1 import V1CheckDomainAvailabilityPostRequest1
from godaddy_python_sdk import configuration


class TestV1CheckDomainAvailabilityPostRequest1(unittest.TestCase):
    """V1CheckDomainAvailabilityPostRequest1 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
