# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import godaddy_python_sdk
from godaddy_python_sdk.model.array_of_dns_record import ArrayOfDNSRecord
from godaddy_python_sdk import configuration


class TestArrayOfDNSRecord(unittest.TestCase):
    """ArrayOfDNSRecord unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
