# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import godaddy_python_sdk
from godaddy_python_sdk.model.json_schema import JsonSchema
from godaddy_python_sdk import configuration


class TestJsonSchema(unittest.TestCase):
    """JsonSchema unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
