# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from godaddy_python_sdk.type.error_field import ErrorField

class RequiredActionReason(TypedDict):
    # Short identifier, suitable for indicating the reason for the current status and how to handle within client code
    code: str

class OptionalActionReason(TypedDict, total=False):
    # List of the specific fields, and the errors found with their contents
    fields: typing.List[ErrorField]

    # Human-readable, English description of the code
    message: str

class ActionReason(RequiredActionReason, OptionalActionReason):
    pass
