# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredConsentV2(TypedDict):
    # Timestamp indicating when the end-user consented to these legal agreements
    agreedAt: str

    # Originating client IP address of the end-user's computer when they consented to these legal agreements
    agreedBy: str

    # Unique identifiers of the legal agreements to which the end-user has agreed, as returned from the/domains/agreements endpoint
    agreementKeys: typing.List[str]

    # Currency in which the `price` is listed
    currency: str

    # Price of the domain excluding taxes or fees. Please use GET /v1/domains/available to retrieve the price and currency for the domain
    price: int

class OptionalConsentV2(TypedDict, total=False):
    # The trademark claim token, only needed if the domain has an active trademark claim
    claimToken: str

    # Only required for hosted registrar if domain is premium. If true indicates that the `price` and `currency` listed are the registry premium price and currency for the domain
    registryPremiumPricing: bool

class ConsentV2(RequiredConsentV2, OptionalConsentV2):
    pass
