# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredConsent(TypedDict):
    # Timestamp indicating when the end-user consented to these legal agreements
    agreedAt: str

    # Originating client IP address of the end-user's computer when they consented to these legal agreements
    agreedBy: str

    # Unique identifiers of the legal agreements to which the end-user has agreed, as returned from the/domains/agreements endpoint
    agreementKeys: typing.List[str]

class OptionalConsent(TypedDict, total=False):
    pass

class Consent(RequiredConsent, OptionalConsent):
    pass
