# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from godaddy_python_sdk.type.address import Address

class RequiredContactDomainCreate(TypedDict):
    addressMailing: Address

    email: str

    # The encoding of the contact data<br/><ul><li><strong style='margin-left: 12px;'>ASCII</strong> - Data contains only ASCII characters that are not region or language specific</li><li><strong style='margin-left: 12px;'>UTF-8</strong> - Data contains characters that are specific to a region or language</li></ul>
    encoding: str

    nameFirst: str

    nameLast: str

    phone: str

class OptionalContactDomainCreate(TypedDict, total=False):
    fax: str

    jobTitle: str

    # The contact eligibility data fields as specified by GET /v2/customers/{customerId}/domains/contacts/schema/{tld}
    metadata: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    nameMiddle: str

    organization: str

class ContactDomainCreate(RequiredContactDomainCreate, OptionalContactDomainCreate):
    pass
