# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDNSRecord(TypedDict):
    data: str

    name: str

    type: str

class OptionalDNSRecord(TypedDict, total=False):
    # Service port (SRV only)
    port: int

    # Record priority (MX and SRV only)
    priority: int

    # Service protocol (SRV only)
    protocol: str

    # Service type (SRV only)
    service: str

    ttl: int

    # Record weight (SRV only)
    weight: int

class DNSRecord(RequiredDNSRecord, OptionalDNSRecord):
    pass
