# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDomainForwardingMask(TypedDict):
    pass

class OptionalDomainForwardingMask(TypedDict, total=False):
    # Displays at the top of the browser window and in search results.
    title: str

    # A short description of your website to display in search engine results.
    description: str

    # A list of comma-separated keywords that describes the content and purpose of your website.
    keywords: str

class DomainForwardingMask(RequiredDomainForwardingMask, OptionalDomainForwardingMask):
    pass
