# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from godaddy_python_sdk.type.consent_v2 import ConsentV2
from godaddy_python_sdk.type.domain_contacts_create_v2 import DomainContactsCreateV2

class RequiredDomainPurchaseV2(TypedDict):
    consent: ConsentV2

    # For internationalized domain names with non-ascii characters, the domain name is converted to punycode before format and pattern validation rules are checked
    domain: str

class OptionalDomainPurchaseV2(TypedDict, total=False):
    contacts: DomainContactsCreateV2

    # The domain eligibility data fields as specified by GET /v2/customers/{customerId}/domains/register/schema/{tld}
    metadata: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    nameServers: typing.List[str]

    period: int

    privacy: bool

    renewAuto: bool

class DomainPurchaseV2(RequiredDomainPurchaseV2, OptionalDomainPurchaseV2):
    pass
