# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDomainPurchaseResponse(TypedDict):
    # Number items included in the order
    itemCount: int

    # Unique identifier of the order processed to purchase the domain
    orderId: int

    # Total cost of the domain and any selected add-ons
    total: int

class OptionalDomainPurchaseResponse(TypedDict, total=False):
    # Currency in which the `total` is listed
    currency: str

class DomainPurchaseResponse(RequiredDomainPurchaseResponse, OptionalDomainPurchaseResponse):
    pass
