# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDomainNotification(TypedDict):
    # The date the notification was added
    addedAt: str

    # The notification ID to be used in POST /v2/customers/{customerId}/domains/notifications to acknowledge the notification
    notificationId: str

    # The resource the notification pertains to.
    resource: str

    # The type of resource the notification relates to
    resourceType: str

    # The resulting status of the action.
    status: str

    # The type of action the notification relates to
    type: str

class OptionalDomainNotification(TypedDict, total=False):
    # The notification data for the given type as specifed by GET /v2/customers/{customerId}/domains/notifications/schema
    metadata: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    # A client provided identifier (via X-Request-Id header) indicating the request this notification is for
    requestId: str

class DomainNotification(RequiredDomainNotification, OptionalDomainNotification):
    pass
