# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDomainAvailableResponse(TypedDict):
    # Whether or not the domain name is available
    available: bool

    # Whether or not the `available` answer has been definitively verified with the registry
    definitive: bool

    # Domain name
    domain: str

class OptionalDomainAvailableResponse(TypedDict, total=False):
    # Currency in which the `price` is listed. Only returned if tld is offered
    currency: str

    # Number of years included in the price. Only returned if tld is offered
    period: int

    # Price of the domain excluding taxes or fees. Only returned if tld is offered
    price: int

class DomainAvailableResponse(RequiredDomainAvailableResponse, OptionalDomainAvailableResponse):
    pass
