# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from godaddy_python_sdk.type.consent_redemption import ConsentRedemption

class RequiredDomainRedeemV2(TypedDict):
    consent: ConsentRedemption

class OptionalDomainRedeemV2(TypedDict, total=False):
    pass

class DomainRedeemV2(RequiredDomainRedeemV2, OptionalDomainRedeemV2):
    pass
