# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from godaddy_python_sdk.type.error_field_domain_contacts_validate import ErrorFieldDomainContactsValidate

class RequiredErrorDomainContactsValidate(TypedDict):
    # Short identifier for the error, suitable for indicating the specific error within client code
    code: str

class OptionalErrorDomainContactsValidate(TypedDict, total=False):
    # List of the specific fields, and the errors found with their contents
    fields: typing.List[ErrorFieldDomainContactsValidate]

    # Human-readable, English description of the error
    message: str

    # Stack trace indicating where the error occurred.<br/>NOTE: This attribute <strong>MAY</strong> be included for Development and Test environments. However, it <strong>MUST NOT</strong> be exposed from OTE nor Production systems
    stack: typing.List[str]

class ErrorDomainContactsValidate(RequiredErrorDomainContactsValidate, OptionalErrorDomainContactsValidate):
    pass
