# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredErrorFieldDomainContactsValidate(TypedDict):
    # Short identifier for the error, suitable for indicating the specific error within client code
    code: str

    # An array of domain names the error is for. If tlds are specified in the request, `domains` will contain tlds. For example, if `domains` in request is [\"test1.com\", \"test2.uk\", \"net\"], and the field is invalid for com and net, then one of the `fields` in response will have [\"test1.com\", \"net\"] as `domains`
    domains: typing.List[str]

    # 1) JSONPath referring to the field within the data containing an error<br/>or<br/>2) JSONPath referring to an object containing an error
    path: str

class OptionalErrorFieldDomainContactsValidate(TypedDict, total=False):
    # Human-readable, English description of the problem with the contents of the field
    message: str

    # JSONPath referring to the field on the object referenced by `path` containing an error
    pathRelated: str

class ErrorFieldDomainContactsValidate(RequiredErrorFieldDomainContactsValidate, OptionalErrorFieldDomainContactsValidate):
    pass
