# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredErrorField(TypedDict):
    # Short identifier for the error, suitable for indicating the specific error within client code
    code: str

    # <ul> <li style='margin-left: 12px;'>JSONPath referring to a field containing an error</li> <strong style='margin-left: 12px;'>OR</strong> <li style='margin-left: 12px;'>JSONPath referring to a field that refers to an object containing an error, with more detail in `pathRelated`</li> </ul>
    path: str

class OptionalErrorField(TypedDict, total=False):
    # Human-readable, English description of the problem with the contents of the field
    message: str

    # JSONPath referring to a field containing an error, which is referenced by `path`
    pathRelated: str

class ErrorField(RequiredErrorField, OptionalErrorField):
    pass
