# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredVerificationDomainName(TypedDict):
    # Status of the domain name verification
    status: str

class OptionalVerificationDomainName(TypedDict, total=False):
    pass

class VerificationDomainName(RequiredVerificationDomainName, OptionalVerificationDomainName):
    pass
