# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import godaddy_python_sdk
from godaddy_python_sdk.paths.v1_domains_domain_privacy_purchase import post
from godaddy_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1DomainsDomainPrivacyPurchase(ApiTestMixin, unittest.TestCase):
    """
    V1DomainsDomainPrivacyPurchase unit test stubs
        Purchase privacy for a specified domain
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200


















if __name__ == '__main__':
    unittest.main()
