# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from godaddy_python_sdk import schemas  # noqa: F401


class ContactDomainCreate(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "nameLast",
            "nameFirst",
            "addressMailing",
            "phone",
            "encoding",
            "email",
        }
        
        class properties:
        
            @staticmethod
            def addressMailing() -> typing.Type['Address']:
                return Address
            
            
            class email(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    format = 'email'
                    max_length = 80
            
            
            class encoding(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "ASCII": "ASCII",
                        "UTF-8": "UTF8",
                    }
                
                @schemas.classproperty
                def ASCII(cls):
                    return cls("ASCII")
                
                @schemas.classproperty
                def UTF8(cls):
                    return cls("UTF-8")
            
            
            class nameFirst(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    format = 'person-name'
                    max_length = 30
            
            
            class nameLast(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    format = 'person-name'
                    max_length = 30
            
            
            class phone(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    format = 'phone'
                    max_length = 17
            
            
            class fax(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    format = 'phone'
                    max_length = 17
            jobTitle = schemas.StrSchema
            metadata = schemas.DictSchema
            nameMiddle = schemas.StrSchema
            
            
            class organization(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    format = 'organization-name'
                    max_length = 100
            __annotations__ = {
                "addressMailing": addressMailing,
                "email": email,
                "encoding": encoding,
                "nameFirst": nameFirst,
                "nameLast": nameLast,
                "phone": phone,
                "fax": fax,
                "jobTitle": jobTitle,
                "metadata": metadata,
                "nameMiddle": nameMiddle,
                "organization": organization,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    nameLast: MetaOapg.properties.nameLast
    nameFirst: MetaOapg.properties.nameFirst
    addressMailing: 'Address'
    phone: MetaOapg.properties.phone
    encoding: MetaOapg.properties.encoding
    email: MetaOapg.properties.email
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nameLast"]) -> MetaOapg.properties.nameLast: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nameFirst"]) -> MetaOapg.properties.nameFirst: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["addressMailing"]) -> 'Address': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phone"]) -> MetaOapg.properties.phone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["encoding"]) -> MetaOapg.properties.encoding: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fax"]) -> MetaOapg.properties.fax: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobTitle"]) -> MetaOapg.properties.jobTitle: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> MetaOapg.properties.metadata: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nameMiddle"]) -> MetaOapg.properties.nameMiddle: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["organization"]) -> MetaOapg.properties.organization: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["nameLast"], typing_extensions.Literal["nameFirst"], typing_extensions.Literal["addressMailing"], typing_extensions.Literal["phone"], typing_extensions.Literal["encoding"], typing_extensions.Literal["email"], typing_extensions.Literal["fax"], typing_extensions.Literal["jobTitle"], typing_extensions.Literal["metadata"], typing_extensions.Literal["nameMiddle"], typing_extensions.Literal["organization"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nameLast"]) -> MetaOapg.properties.nameLast: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nameFirst"]) -> MetaOapg.properties.nameFirst: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["addressMailing"]) -> 'Address': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phone"]) -> MetaOapg.properties.phone: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["encoding"]) -> MetaOapg.properties.encoding: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fax"]) -> typing.Union[MetaOapg.properties.fax, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobTitle"]) -> typing.Union[MetaOapg.properties.jobTitle, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union[MetaOapg.properties.metadata, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nameMiddle"]) -> typing.Union[MetaOapg.properties.nameMiddle, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["organization"]) -> typing.Union[MetaOapg.properties.organization, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["nameLast"], typing_extensions.Literal["nameFirst"], typing_extensions.Literal["addressMailing"], typing_extensions.Literal["phone"], typing_extensions.Literal["encoding"], typing_extensions.Literal["email"], typing_extensions.Literal["fax"], typing_extensions.Literal["jobTitle"], typing_extensions.Literal["metadata"], typing_extensions.Literal["nameMiddle"], typing_extensions.Literal["organization"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        nameLast: typing.Union[MetaOapg.properties.nameLast, str, ],
        nameFirst: typing.Union[MetaOapg.properties.nameFirst, str, ],
        addressMailing: 'Address',
        phone: typing.Union[MetaOapg.properties.phone, str, ],
        encoding: typing.Union[MetaOapg.properties.encoding, str, ],
        email: typing.Union[MetaOapg.properties.email, str, ],
        fax: typing.Union[MetaOapg.properties.fax, str, schemas.Unset] = schemas.unset,
        jobTitle: typing.Union[MetaOapg.properties.jobTitle, str, schemas.Unset] = schemas.unset,
        metadata: typing.Union[MetaOapg.properties.metadata, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        nameMiddle: typing.Union[MetaOapg.properties.nameMiddle, str, schemas.Unset] = schemas.unset,
        organization: typing.Union[MetaOapg.properties.organization, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs,
    ) -> 'ContactDomainCreate':
        return super().__new__(
            cls,
            *args,
            nameLast=nameLast,
            nameFirst=nameFirst,
            addressMailing=addressMailing,
            phone=phone,
            encoding=encoding,
            email=email,
            fax=fax,
            jobTitle=jobTitle,
            metadata=metadata,
            nameMiddle=nameMiddle,
            organization=organization,
            _configuration=_configuration,
        )

from godaddy_python_sdk.model.address import Address
