# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from godaddy_python_sdk import schemas  # noqa: F401


class DomainTransferInV2(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "authCode",
            "consent",
        }
        
        class properties:
            authCode = schemas.StrSchema
        
            @staticmethod
            def consent() -> typing.Type['ConsentV2']:
                return ConsentV2
        
            @staticmethod
            def contacts() -> typing.Type['DomainContactsCreateV2']:
                return DomainContactsCreateV2
            identityDocumentId = schemas.StrSchema
            metadata = schemas.DictSchema
            
            
            class period(
                schemas.IntSchema
            ):
            
            
                class MetaOapg:
                    format = 'integer-positive'
                    inclusive_maximum = 10
                    inclusive_minimum = 1
            privacy = schemas.BoolSchema
            renewAuto = schemas.BoolSchema
            __annotations__ = {
                "authCode": authCode,
                "consent": consent,
                "contacts": contacts,
                "identityDocumentId": identityDocumentId,
                "metadata": metadata,
                "period": period,
                "privacy": privacy,
                "renewAuto": renewAuto,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    authCode: MetaOapg.properties.authCode
    consent: 'ConsentV2'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["authCode"]) -> MetaOapg.properties.authCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["consent"]) -> 'ConsentV2': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contacts"]) -> 'DomainContactsCreateV2': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["identityDocumentId"]) -> MetaOapg.properties.identityDocumentId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> MetaOapg.properties.metadata: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["period"]) -> MetaOapg.properties.period: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["privacy"]) -> MetaOapg.properties.privacy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["renewAuto"]) -> MetaOapg.properties.renewAuto: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["authCode"], typing_extensions.Literal["consent"], typing_extensions.Literal["contacts"], typing_extensions.Literal["identityDocumentId"], typing_extensions.Literal["metadata"], typing_extensions.Literal["period"], typing_extensions.Literal["privacy"], typing_extensions.Literal["renewAuto"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["authCode"]) -> MetaOapg.properties.authCode: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["consent"]) -> 'ConsentV2': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contacts"]) -> typing.Union['DomainContactsCreateV2', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["identityDocumentId"]) -> typing.Union[MetaOapg.properties.identityDocumentId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union[MetaOapg.properties.metadata, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["period"]) -> typing.Union[MetaOapg.properties.period, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["privacy"]) -> typing.Union[MetaOapg.properties.privacy, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["renewAuto"]) -> typing.Union[MetaOapg.properties.renewAuto, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["authCode"], typing_extensions.Literal["consent"], typing_extensions.Literal["contacts"], typing_extensions.Literal["identityDocumentId"], typing_extensions.Literal["metadata"], typing_extensions.Literal["period"], typing_extensions.Literal["privacy"], typing_extensions.Literal["renewAuto"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        authCode: typing.Union[MetaOapg.properties.authCode, str, ],
        consent: 'ConsentV2',
        contacts: typing.Union['DomainContactsCreateV2', schemas.Unset] = schemas.unset,
        identityDocumentId: typing.Union[MetaOapg.properties.identityDocumentId, str, schemas.Unset] = schemas.unset,
        metadata: typing.Union[MetaOapg.properties.metadata, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        period: typing.Union[MetaOapg.properties.period, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        privacy: typing.Union[MetaOapg.properties.privacy, bool, schemas.Unset] = schemas.unset,
        renewAuto: typing.Union[MetaOapg.properties.renewAuto, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs,
    ) -> 'DomainTransferInV2':
        return super().__new__(
            cls,
            *args,
            authCode=authCode,
            consent=consent,
            contacts=contacts,
            identityDocumentId=identityDocumentId,
            metadata=metadata,
            period=period,
            privacy=privacy,
            renewAuto=renewAuto,
            _configuration=_configuration,
        )

from godaddy_python_sdk.model.consent_v2 import ConsentV2
from godaddy_python_sdk.model.domain_contacts_create_v2 import DomainContactsCreateV2
