# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from godaddy_python_sdk import schemas  # noqa: F401


class DomainRedeemV2(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "consent",
        }
        
        class properties:
        
            @staticmethod
            def consent() -> typing.Type['ConsentRedemption']:
                return ConsentRedemption
            __annotations__ = {
                "consent": consent,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    consent: 'ConsentRedemption'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["consent"]) -> 'ConsentRedemption': ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["consent"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["consent"]) -> 'ConsentRedemption': ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["consent"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        consent: 'ConsentRedemption',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs,
    ) -> 'DomainRedeemV2':
        return super().__new__(
            cls,
            *args,
            consent=consent,
            _configuration=_configuration,
        )

from godaddy_python_sdk.model.consent_redemption import ConsentRedemption
