# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import godaddy_python_sdk
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_register_schema_tld import get
from godaddy_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV2CustomersCustomerIdDomainsRegisterSchemaTld(ApiTestMixin, unittest.TestCase):
    """
    V2CustomersCustomerIdDomainsRegisterSchemaTld unit test stubs
        Retrieve the schema to be submitted when registering a Domain for the specified TLD
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
