# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from godaddy_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from godaddy_python_sdk.api_response import AsyncGeneratorResponse
from godaddy_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from godaddy_python_sdk import schemas  # noqa: F401

from godaddy_python_sdk.model.domains_contacts_bulk import DomainsContactsBulk as DomainsContactsBulkSchema
from godaddy_python_sdk.model.contact import Contact as ContactSchema
from godaddy_python_sdk.model.error import Error as ErrorSchema
from godaddy_python_sdk.model.error_domain_contacts_validate import ErrorDomainContactsValidate as ErrorDomainContactsValidateSchema
from godaddy_python_sdk.model.error_limit import ErrorLimit as ErrorLimitSchema

from godaddy_python_sdk.type.contact import Contact
from godaddy_python_sdk.type.domains_contacts_bulk import DomainsContactsBulk
from godaddy_python_sdk.type.error_domain_contacts_validate import ErrorDomainContactsValidate
from godaddy_python_sdk.type.error import Error
from godaddy_python_sdk.type.error_limit import ErrorLimit

from ...api_client import Dictionary
from godaddy_python_sdk.pydantic.contact import Contact as ContactPydantic
from godaddy_python_sdk.pydantic.error_limit import ErrorLimit as ErrorLimitPydantic
from godaddy_python_sdk.pydantic.error import Error as ErrorPydantic
from godaddy_python_sdk.pydantic.domains_contacts_bulk import DomainsContactsBulk as DomainsContactsBulkPydantic
from godaddy_python_sdk.pydantic.error_domain_contacts_validate import ErrorDomainContactsValidate as ErrorDomainContactsValidatePydantic

# Query params
MarketIdSchema = schemas.StrSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'marketId': typing.Union[MarketIdSchema, str, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_market_id = api_client.QueryParameter(
    name="marketId",
    style=api_client.ParameterStyle.FORM,
    schema=MarketIdSchema,
    explode=True,
)
# Header params
XPrivateLabelIdSchema = schemas.IntSchema
RequestRequiredHeaderParams = typing_extensions.TypedDict(
    'RequestRequiredHeaderParams',
    {
    }
)
RequestOptionalHeaderParams = typing_extensions.TypedDict(
    'RequestOptionalHeaderParams',
    {
        'X-Private-Label-Id': typing.Union[XPrivateLabelIdSchema, decimal.Decimal, int, ],
    },
    total=False
)


class RequestHeaderParams(RequestRequiredHeaderParams, RequestOptionalHeaderParams):
    pass


request_header_x_private_label_id = api_client.HeaderParameter(
    name="X-Private-Label-Id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=XPrivateLabelIdSchema,
)
# body param
SchemaForRequestBodyApplicationJson = DomainsContactsBulkSchema
SchemaForRequestBodyApplicationXml = DomainsContactsBulkSchema
SchemaForRequestBodyTextXml = DomainsContactsBulkSchema


request_body_domains_contacts_bulk = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
        'application/xml': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationXml),
        'text/xml': api_client.MediaType(
            schema=SchemaForRequestBodyTextXml),
    },
    required=True,
)


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
)


@dataclass
class ApiResponseFor204(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor204Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_204 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor204,
    response_cls_async=ApiResponseFor204Async,
)
SchemaFor400ResponseBodyApplicationJson = ErrorSchema
SchemaFor400ResponseBodyApplicationJavascript = ErrorSchema
SchemaFor400ResponseBodyApplicationXml = ErrorSchema
SchemaFor400ResponseBodyTextJavascript = ErrorSchema
SchemaFor400ResponseBodyTextXml = ErrorSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: Error


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: Error


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
        'application/javascript': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJavascript),
        'application/xml': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationXml),
        'text/javascript': api_client.MediaType(
            schema=SchemaFor400ResponseBodyTextJavascript),
        'text/xml': api_client.MediaType(
            schema=SchemaFor400ResponseBodyTextXml),
    },
)
SchemaFor422ResponseBodyApplicationJson = ErrorDomainContactsValidateSchema
SchemaFor422ResponseBodyApplicationJavascript = ErrorDomainContactsValidateSchema
SchemaFor422ResponseBodyApplicationXml = ErrorDomainContactsValidateSchema
SchemaFor422ResponseBodyTextJavascript = ErrorDomainContactsValidateSchema
SchemaFor422ResponseBodyTextXml = ErrorDomainContactsValidateSchema


@dataclass
class ApiResponseFor422(api_client.ApiResponse):
    body: ErrorDomainContactsValidate


@dataclass
class ApiResponseFor422Async(api_client.AsyncApiResponse):
    body: ErrorDomainContactsValidate


_response_for_422 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor422,
    response_cls_async=ApiResponseFor422Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor422ResponseBodyApplicationJson),
        'application/javascript': api_client.MediaType(
            schema=SchemaFor422ResponseBodyApplicationJavascript),
        'application/xml': api_client.MediaType(
            schema=SchemaFor422ResponseBodyApplicationXml),
        'text/javascript': api_client.MediaType(
            schema=SchemaFor422ResponseBodyTextJavascript),
        'text/xml': api_client.MediaType(
            schema=SchemaFor422ResponseBodyTextXml),
    },
)
SchemaFor429ResponseBodyApplicationJson = ErrorLimitSchema
SchemaFor429ResponseBodyApplicationJavascript = ErrorLimitSchema
SchemaFor429ResponseBodyApplicationXml = ErrorLimitSchema
SchemaFor429ResponseBodyTextJavascript = ErrorLimitSchema
SchemaFor429ResponseBodyTextXml = ErrorLimitSchema


@dataclass
class ApiResponseFor429(api_client.ApiResponse):
    body: ErrorLimit


@dataclass
class ApiResponseFor429Async(api_client.AsyncApiResponse):
    body: ErrorLimit


_response_for_429 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor429,
    response_cls_async=ApiResponseFor429Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor429ResponseBodyApplicationJson),
        'application/javascript': api_client.MediaType(
            schema=SchemaFor429ResponseBodyApplicationJavascript),
        'application/xml': api_client.MediaType(
            schema=SchemaFor429ResponseBodyApplicationXml),
        'text/javascript': api_client.MediaType(
            schema=SchemaFor429ResponseBodyTextJavascript),
        'text/xml': api_client.MediaType(
            schema=SchemaFor429ResponseBodyTextXml),
    },
)
SchemaFor500ResponseBodyApplicationJson = ErrorSchema
SchemaFor500ResponseBodyApplicationJavascript = ErrorSchema
SchemaFor500ResponseBodyApplicationXml = ErrorSchema
SchemaFor500ResponseBodyTextJavascript = ErrorSchema
SchemaFor500ResponseBodyTextXml = ErrorSchema


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: Error


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: Error


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationJson),
        'application/javascript': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationJavascript),
        'application/xml': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationXml),
        'text/javascript': api_client.MediaType(
            schema=SchemaFor500ResponseBodyTextJavascript),
        'text/xml': api_client.MediaType(
            schema=SchemaFor500ResponseBodyTextXml),
    },
)
_all_accept_content_types = (
    'application/json',
    'application/javascript',
    'application/xml',
    'text/javascript',
    'text/xml',
)


class BaseApi(api_client.Api):

    def _validate_domain_contacts_mapped_args(
        self,
        domains: typing.List[str],
        contact_admin: typing.Optional[Contact] = None,
        contact_billing: typing.Optional[Contact] = None,
        contact_presence: typing.Optional[Contact] = None,
        contact_registrant: typing.Optional[Contact] = None,
        contact_tech: typing.Optional[Contact] = None,
        entity_type: typing.Optional[str] = None,
        x_private_label_id: typing.Optional[int] = None,
        market_id: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _header_params = {}
        _body = {}
        if contact_admin is not None:
            _body["contactAdmin"] = contact_admin
        if contact_billing is not None:
            _body["contactBilling"] = contact_billing
        if contact_presence is not None:
            _body["contactPresence"] = contact_presence
        if contact_registrant is not None:
            _body["contactRegistrant"] = contact_registrant
        if contact_tech is not None:
            _body["contactTech"] = contact_tech
        if domains is not None:
            _body["domains"] = domains
        if entity_type is not None:
            _body["entityType"] = entity_type
        args.body = _body
        if market_id is not None:
            _query_params["marketId"] = market_id
        if x_private_label_id is not None:
            _header_params["X-Private-Label-Id"] = x_private_label_id
        args.query = _query_params
        args.header = _header_params
        return args

    async def _avalidate_domain_contacts_oapg(
        self,
        body: typing.Any = None,
            query_params: typing.Optional[dict] = {},
            header_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseFor204Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Validate the request body using the Domain Contact Validation Schema for specified domains.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestHeaderParams, header_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_market_id,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        for parameter in (
            request_header_x_private_label_id,
        ):
            parameter_data = header_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _headers.extend(serialized_data)
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/domains/contacts/validate',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_domains_contacts_bulk.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _validate_domain_contacts_oapg(
        self,
        body: typing.Any = None,
            query_params: typing.Optional[dict] = {},
            header_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseFor204,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Validate the request body using the Domain Contact Validation Schema for specified domains.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestHeaderParams, header_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_market_id,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        for parameter in (
            request_header_x_private_label_id,
        ):
            parameter_data = header_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _headers.extend(serialized_data)
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/domains/contacts/validate',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_domains_contacts_bulk.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ValidateDomainContactsRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def avalidate_domain_contacts(
        self,
        domains: typing.List[str],
        contact_admin: typing.Optional[Contact] = None,
        contact_billing: typing.Optional[Contact] = None,
        contact_presence: typing.Optional[Contact] = None,
        contact_registrant: typing.Optional[Contact] = None,
        contact_tech: typing.Optional[Contact] = None,
        entity_type: typing.Optional[str] = None,
        x_private_label_id: typing.Optional[int] = None,
        market_id: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseFor204Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._validate_domain_contacts_mapped_args(
            body=body,
            domains=domains,
            contact_admin=contact_admin,
            contact_billing=contact_billing,
            contact_presence=contact_presence,
            contact_registrant=contact_registrant,
            contact_tech=contact_tech,
            entity_type=entity_type,
            x_private_label_id=x_private_label_id,
            market_id=market_id,
        )
        return await self._avalidate_domain_contacts_oapg(
            body=args.body,
            query_params=args.query,
            header_params=args.header,
            **kwargs,
        )
    
    def validate_domain_contacts(
        self,
        domains: typing.List[str],
        contact_admin: typing.Optional[Contact] = None,
        contact_billing: typing.Optional[Contact] = None,
        contact_presence: typing.Optional[Contact] = None,
        contact_registrant: typing.Optional[Contact] = None,
        contact_tech: typing.Optional[Contact] = None,
        entity_type: typing.Optional[str] = None,
        x_private_label_id: typing.Optional[int] = None,
        market_id: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseFor204,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._validate_domain_contacts_mapped_args(
            body=body,
            domains=domains,
            contact_admin=contact_admin,
            contact_billing=contact_billing,
            contact_presence=contact_presence,
            contact_registrant=contact_registrant,
            contact_tech=contact_tech,
            entity_type=entity_type,
            x_private_label_id=x_private_label_id,
            market_id=market_id,
        )
        return self._validate_domain_contacts_oapg(
            body=args.body,
            query_params=args.query,
            header_params=args.header,
        )

class ValidateDomainContacts(BaseApi):

    async def avalidate_domain_contacts(
        self,
        domains: typing.List[str],
        contact_admin: typing.Optional[Contact] = None,
        contact_billing: typing.Optional[Contact] = None,
        contact_presence: typing.Optional[Contact] = None,
        contact_registrant: typing.Optional[Contact] = None,
        contact_tech: typing.Optional[Contact] = None,
        entity_type: typing.Optional[str] = None,
        x_private_label_id: typing.Optional[int] = None,
        market_id: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> None:
        raw_response = await self.raw.avalidate_domain_contacts(
            body=body,
            domains=domains,
            contact_admin=contact_admin,
            contact_billing=contact_billing,
            contact_presence=contact_presence,
            contact_registrant=contact_registrant,
            contact_tech=contact_tech,
            entity_type=entity_type,
            x_private_label_id=x_private_label_id,
            market_id=market_id,
            **kwargs,
        )
    
    
    def validate_domain_contacts(
        self,
        domains: typing.List[str],
        contact_admin: typing.Optional[Contact] = None,
        contact_billing: typing.Optional[Contact] = None,
        contact_presence: typing.Optional[Contact] = None,
        contact_registrant: typing.Optional[Contact] = None,
        contact_tech: typing.Optional[Contact] = None,
        entity_type: typing.Optional[str] = None,
        x_private_label_id: typing.Optional[int] = None,
        market_id: typing.Optional[str] = None,
        validate: bool = False,
    ) -> None:
        raw_response = self.raw.validate_domain_contacts(
            body=body,
            domains=domains,
            contact_admin=contact_admin,
            contact_billing=contact_billing,
            contact_presence=contact_presence,
            contact_registrant=contact_registrant,
            contact_tech=contact_tech,
            entity_type=entity_type,
            x_private_label_id=x_private_label_id,
            market_id=market_id,
        )


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        domains: typing.List[str],
        contact_admin: typing.Optional[Contact] = None,
        contact_billing: typing.Optional[Contact] = None,
        contact_presence: typing.Optional[Contact] = None,
        contact_registrant: typing.Optional[Contact] = None,
        contact_tech: typing.Optional[Contact] = None,
        entity_type: typing.Optional[str] = None,
        x_private_label_id: typing.Optional[int] = None,
        market_id: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseFor204Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._validate_domain_contacts_mapped_args(
            body=body,
            domains=domains,
            contact_admin=contact_admin,
            contact_billing=contact_billing,
            contact_presence=contact_presence,
            contact_registrant=contact_registrant,
            contact_tech=contact_tech,
            entity_type=entity_type,
            x_private_label_id=x_private_label_id,
            market_id=market_id,
        )
        return await self._avalidate_domain_contacts_oapg(
            body=args.body,
            query_params=args.query,
            header_params=args.header,
            **kwargs,
        )
    
    def post(
        self,
        domains: typing.List[str],
        contact_admin: typing.Optional[Contact] = None,
        contact_billing: typing.Optional[Contact] = None,
        contact_presence: typing.Optional[Contact] = None,
        contact_registrant: typing.Optional[Contact] = None,
        contact_tech: typing.Optional[Contact] = None,
        entity_type: typing.Optional[str] = None,
        x_private_label_id: typing.Optional[int] = None,
        market_id: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseFor204,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._validate_domain_contacts_mapped_args(
            body=body,
            domains=domains,
            contact_admin=contact_admin,
            contact_billing=contact_billing,
            contact_presence=contact_presence,
            contact_registrant=contact_registrant,
            contact_tech=contact_tech,
            entity_type=entity_type,
            x_private_label_id=x_private_label_id,
            market_id=market_id,
        )
        return self._validate_domain_contacts_oapg(
            body=args.body,
            query_params=args.query,
            header_params=args.header,
        )

