# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from godaddy_python_sdk.paths.v2_customers_customer_id_domains_domain_transfer_in_accept.post import AcceptTransferInRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_domain_transfer_out_accept.post import AcceptTransferOutRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_forwards_fqdn.delete import CancelForwardingRequestRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_domain_transfer_in_cancel.post import CancelTransferInRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_forwards_fqdn.post import CreateForwardingConfigurationRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_domain.get import GetDetailsRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_forwards_fqdn.get import GetForwardingInfoRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_register_schema_tld.get import GetRegisterSchemaRaw
from godaddy_python_sdk.paths.v2_domains_maintenances_maintenance_id.get import GetUpcomingMaintenanceDetailsRaw
from godaddy_python_sdk.paths.v2_domains_maintenances.get import GetUpcomingMaintenancesListRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_domain_transfer_out.post import InitiateTransferOutRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_forwards_fqdn.put import ModifyForwardingInfoRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_register.post import PurchaseRegisterDomainRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_domain_transfer.post import PurchaseTransferProcessRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_domain_redeem.post import RedeemDomainRestoreRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_domain_transfer_out_reject.post import RejectTransferOutRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_domain_renew.post import RenewDomainRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_domain_transfer_in_restart.post import RestartTransferInRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_domain_transfer_in_retry.post import RetryTransferInProcessRaw
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_register_validate.post import ValidateDomainRegistrationRaw


class DomainsApiRaw(
    AcceptTransferInRaw,
    AcceptTransferOutRaw,
    CancelForwardingRequestRaw,
    CancelTransferInRaw,
    CreateForwardingConfigurationRaw,
    GetDetailsRaw,
    GetForwardingInfoRaw,
    GetRegisterSchemaRaw,
    GetUpcomingMaintenanceDetailsRaw,
    GetUpcomingMaintenancesListRaw,
    InitiateTransferOutRaw,
    ModifyForwardingInfoRaw,
    PurchaseRegisterDomainRaw,
    PurchaseTransferProcessRaw,
    RedeemDomainRestoreRaw,
    RejectTransferOutRaw,
    RenewDomainRaw,
    RestartTransferInRaw,
    RetryTransferInProcessRaw,
    ValidateDomainRegistrationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
