# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from godaddy_python_sdk.paths.v2_customers_customer_id_domains_notifications_notification_id_acknowledge.post import AcknowledgeDomainNotification
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_notifications.get import GetNextDomain
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_notifications_schemas_type.get import GetSchema
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_notifications_opt_in.get import ListOptedInTypes
from godaddy_python_sdk.paths.v2_customers_customer_id_domains_notifications_opt_in.put import OptInNotifications
from godaddy_python_sdk.apis.tags.notifications_api_raw import NotificationsApiRaw


class NotificationsApi(
    AcknowledgeDomainNotification,
    GetNextDomain,
    GetSchema,
    ListOptedInTypes,
    OptInNotifications,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: NotificationsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = NotificationsApiRaw(api_client)
