# coding: utf-8

"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from godaddy_python_sdk.paths.v1_domains_domain_records.patch import AddDnsRecordsToDomainRaw
from godaddy_python_sdk.paths.v1_domains_domain.delete import CancelDomainPurchaseRaw
from godaddy_python_sdk.paths.v1_domains_domain_privacy.delete import CancelPrivacyRequestRaw
from godaddy_python_sdk.paths.v1_domains_available.get import CheckDomainAvailabilityRaw
from godaddy_python_sdk.paths.v1_domains_available.post import CheckDomainAvailabilityPostRaw
from godaddy_python_sdk.paths.v1_domains_purchase.post import CreateDomainPurchaseRaw
from godaddy_python_sdk.paths.v1_domains_domain_records_type_name.delete import DeleteAllDnsRecordsRaw
from godaddy_python_sdk.paths.v1_domains_domain_records_type_name.get import GetDnsRecordsRaw
from godaddy_python_sdk.paths.v1_domains_domain.get import GetDomainDetailsRaw
from godaddy_python_sdk.paths.v1_domains_purchase_schema_tld.get import GetDomainSchemaRaw
from godaddy_python_sdk.paths.v1_domains.get import GetDomainsListRaw
from godaddy_python_sdk.paths.v1_domains_agreements.get import GetLegalAgreementsRaw
from godaddy_python_sdk.paths.v1_domains_tlds.get import GetTldsListRaw
from godaddy_python_sdk.paths.v1_domains_domain_privacy_purchase.post import PurchasePrivacyForDomainRaw
from godaddy_python_sdk.paths.v1_domains_domain_transfer.post import PurchaseTransferProcessRaw
from godaddy_python_sdk.paths.v1_domains_domain_renew.post import RenewDomainRaw
from godaddy_python_sdk.paths.v1_domains_domain_records.put import ReplaceDnsRecordsRaw
from godaddy_python_sdk.paths.v1_domains_domain_records_type.put import ReplaceDnsRecordsTypeRaw
from godaddy_python_sdk.paths.v1_domains_domain_records_type_name.put import ReplaceDnsRecordsType0Raw
from godaddy_python_sdk.paths.v1_domains_domain_verify_registrant_email.post import ResendContactEmailVerificationRaw
from godaddy_python_sdk.paths.v1_domains_suggest.get import SuggestAlternateDomainsRaw
from godaddy_python_sdk.paths.v1_domains_domain_contacts.patch import UpdateDomainContactsRaw
from godaddy_python_sdk.paths.v1_domains_domain.patch import UpdateDomainDetailsRaw
from godaddy_python_sdk.paths.v1_domains_contacts_validate.post import ValidateDomainContactsRaw
from godaddy_python_sdk.paths.v1_domains_purchase_validate.post import ValidateDomainPurchaseRaw


class V1ApiRaw(
    AddDnsRecordsToDomainRaw,
    CancelDomainPurchaseRaw,
    CancelPrivacyRequestRaw,
    CheckDomainAvailabilityRaw,
    CheckDomainAvailabilityPostRaw,
    CreateDomainPurchaseRaw,
    DeleteAllDnsRecordsRaw,
    GetDnsRecordsRaw,
    GetDomainDetailsRaw,
    GetDomainSchemaRaw,
    GetDomainsListRaw,
    GetLegalAgreementsRaw,
    GetTldsListRaw,
    PurchasePrivacyForDomainRaw,
    PurchaseTransferProcessRaw,
    RenewDomainRaw,
    ReplaceDnsRecordsRaw,
    ReplaceDnsRecordsTypeRaw,
    ReplaceDnsRecordsType0Raw,
    ResendContactEmailVerificationRaw,
    SuggestAlternateDomainsRaw,
    UpdateDomainContactsRaw,
    UpdateDomainDetailsRaw,
    ValidateDomainContactsRaw,
    ValidateDomainPurchaseRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
