# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from godaddy_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    V1_DOMAINS = "/v1/domains"
    V1_DOMAINS_AGREEMENTS = "/v1/domains/agreements"
    V1_DOMAINS_AVAILABLE = "/v1/domains/available"
    V1_DOMAINS_CONTACTS_VALIDATE = "/v1/domains/contacts/validate"
    V1_DOMAINS_PURCHASE = "/v1/domains/purchase"
    V1_DOMAINS_PURCHASE_SCHEMA_TLD = "/v1/domains/purchase/schema/{tld}"
    V1_DOMAINS_PURCHASE_VALIDATE = "/v1/domains/purchase/validate"
    V1_DOMAINS_SUGGEST = "/v1/domains/suggest"
    V1_DOMAINS_TLDS = "/v1/domains/tlds"
    V1_DOMAINS_DOMAIN = "/v1/domains/{domain}"
    V1_DOMAINS_DOMAIN_CONTACTS = "/v1/domains/{domain}/contacts"
    V1_DOMAINS_DOMAIN_PRIVACY = "/v1/domains/{domain}/privacy"
    V1_DOMAINS_DOMAIN_PRIVACY_PURCHASE = "/v1/domains/{domain}/privacy/purchase"
    V1_DOMAINS_DOMAIN_RECORDS = "/v1/domains/{domain}/records"
    V1_DOMAINS_DOMAIN_RECORDS_TYPE = "/v1/domains/{domain}/records/{type}"
    V1_DOMAINS_DOMAIN_RECORDS_TYPE_NAME = "/v1/domains/{domain}/records/{type}/{name}"
    V1_DOMAINS_DOMAIN_RENEW = "/v1/domains/{domain}/renew"
    V1_DOMAINS_DOMAIN_TRANSFER = "/v1/domains/{domain}/transfer"
    V1_DOMAINS_DOMAIN_VERIFY_REGISTRANT_EMAIL = "/v1/domains/{domain}/verifyRegistrantEmail"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_FORWARDS_FQDN = "/v2/customers/{customerId}/domains/forwards/{fqdn}"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_NOTIFICATIONS = "/v2/customers/{customerId}/domains/notifications"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_NOTIFICATIONS_OPT_IN = "/v2/customers/{customerId}/domains/notifications/optIn"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_NOTIFICATIONS_SCHEMAS_TYPE = "/v2/customers/{customerId}/domains/notifications/schemas/{type}"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_NOTIFICATIONS_NOTIFICATION_ID_ACKNOWLEDGE = "/v2/customers/{customerId}/domains/notifications/{notificationId}/acknowledge"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_REGISTER = "/v2/customers/{customerId}/domains/register"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_REGISTER_SCHEMA_TLD = "/v2/customers/{customerId}/domains/register/schema/{tld}"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_REGISTER_VALIDATE = "/v2/customers/{customerId}/domains/register/validate"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN = "/v2/customers/{customerId}/domains/{domain}"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN_ACTIONS = "/v2/customers/{customerId}/domains/{domain}/actions"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN_ACTIONS_TYPE = "/v2/customers/{customerId}/domains/{domain}/actions/{type}"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN_REDEEM = "/v2/customers/{customerId}/domains/{domain}/redeem"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN_RENEW = "/v2/customers/{customerId}/domains/{domain}/renew"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN_TRANSFER = "/v2/customers/{customerId}/domains/{domain}/transfer"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN_TRANSFER_IN_ACCEPT = "/v2/customers/{customerId}/domains/{domain}/transferInAccept"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN_TRANSFER_IN_CANCEL = "/v2/customers/{customerId}/domains/{domain}/transferInCancel"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN_TRANSFER_IN_RESTART = "/v2/customers/{customerId}/domains/{domain}/transferInRestart"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN_TRANSFER_IN_RETRY = "/v2/customers/{customerId}/domains/{domain}/transferInRetry"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN_TRANSFER_OUT = "/v2/customers/{customerId}/domains/{domain}/transferOut"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN_TRANSFER_OUT_ACCEPT = "/v2/customers/{customerId}/domains/{domain}/transferOutAccept"
    V2_CUSTOMERS_CUSTOMER_ID_DOMAINS_DOMAIN_TRANSFER_OUT_REJECT = "/v2/customers/{customerId}/domains/{domain}/transferOutReject"
    V2_DOMAINS_MAINTENANCES = "/v2/domains/maintenances"
    V2_DOMAINS_MAINTENANCES_MAINTENANCE_ID = "/v2/domains/maintenances/{maintenanceId}"
