# coding: utf-8
"""
    All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from godaddy_python_sdk.client_custom import ClientCustom
from godaddy_python_sdk.configuration import Configuration
from godaddy_python_sdk.api_client import ApiClient
from godaddy_python_sdk.type_util import copy_signature
from godaddy_python_sdk.apis.tags.actions_api import ActionsApi
from godaddy_python_sdk.apis.tags.domains_api import DomainsApi
from godaddy_python_sdk.apis.tags.notifications_api import NotificationsApi
from godaddy_python_sdk.apis.tags.v1_api import V1Api



class GoDaddy(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.actions: ActionsApi = ActionsApi(api_client)
        self.domains: DomainsApi = DomainsApi(api_client)
        self.notifications: NotificationsApi = NotificationsApi(api_client)
        self.v1: V1Api = V1Api(api_client)
